export const SET_AUTHORIZATION_TOKEN = 'SET_AUTHORIZATION_TOKEN';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const SET_LOGED_IN = 'SET_LOGED_IN';
export const SET_LOGED_IN_USER_PIN = 'SET_LOGED_IN_USER_PIN';